name: Build and Deploy to Google Cloud Run

on:
  push:
    branches:
      - main  # Set this to the branch name from which you want to deploy

jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Build Docker Image
      run: |
        gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-web-app

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy my-web-app --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-web-app --platform managed --region us-central1 --allow-unauthenticated
